id: ICAA09BFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:11:57+00:00'
last_modified: '2022-06-09T07:02:24.401242+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28975
  title: ནད་རྟགས་ཕྱོགས་བསྒྲིགས་ཀུན་གསལ་ཤེལ་གྱི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    02F4:
      image_group_id: I1PD30323
      title: Volume 1 of nad rtags phyogs bsgrigs kun gsal shes gyi me long
      total_pages: 456
      order: 1
      base_file: 02F4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
