id: P007884
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W28975
  title: ནད་རྟགས་ཕྱོགས་བསྒྲིགས་ཀུན་གསལ་ཤེལ་གྱི་མེ་ལོང་།
  author: ''
  volumes:
    77fc4632c5064003a47aadb8d0922dc8:
      image_group_id: I1PD30323
      title: Volume 1 of nad rtags phyogs bsgrigs kun gsal shes gyi me long
      volume_number: 1
      total_pages: 456
      base_file: v001.txt
