id: P007884
initial_creation_type: ocr
source_metadata:
  id: bdr:W28975
  title: ནད་རྟགས་ཕྱོགས་བསྒྲིགས་ཀུན་གསལ་ཤེལ་གྱི་མེ་ལོང་།
  author: ''
  volumes:
    2cfa1a007c184ea4a8847f9352531d37:
      image_group_id: I1PD30323
      title: ''
      volume_number: 1
      total_pages: 456
ebook_metadata:
  title: ནད་རྟགས་ཕྱོགས་བསྒྲིགས་ཀུན་གསལ་ཤེལ་གྱི་མེ་ལོང་།
  author: ''
  sku: P007884
  cover: cover.jpg
  layers:
  - pagination
